package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (FatalAttribute)
// DB Table: Plural (fatal_attributes)
// Resource: Plural (FatalAttributes)
// Path: Plural (/fatal_attributes)
// View Template Folder: Plural (/templates/fatal_attributes/)

// FatalAttributesResource is the resource for the FatalAttribute model
type FatalAttributesResource struct {
	buffalo.Resource
}

// List gets all FatalAttributes. This function is mapped to the path
// GET /fatal_attributes
func (v FatalAttributesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	fatalAttributes := &models.FatalAttributes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all FatalAttributes from the DB
	if err := q.All(fatalAttributes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, fatalAttributes))
}

// Show gets the data for one FatalAttribute. This function is mapped to
// the path GET /fatal_attributes/{fatal_attribute_id}
func (v FatalAttributesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty FatalAttribute
	fatalAttribute := &models.FatalAttribute{}

	// To find the FatalAttribute the parameter fatal_attribute_id is used.
	if err := tx.Find(fatalAttribute, c.Param("fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, fatalAttribute))
}

// New renders the form for creating a new FatalAttribute.
// This function is mapped to the path GET /fatal_attributes/new
func (v FatalAttributesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.FatalAttribute{}))
}

// Create adds a FatalAttribute to the DB. This function is mapped to the
// path POST /fatal_attributes
func (v FatalAttributesResource) Create(c buffalo.Context) error {
	// Allocate an empty FatalAttribute
	fatalAttribute := &models.FatalAttribute{}

	// Bind fatalAttribute to the html form elements
	if err := c.Bind(fatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(fatalAttribute)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, fatalAttribute))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "FatalAttribute was created successfully")

	// and redirect to the fatal_attributes index page
	return c.Render(201, r.Auto(c, fatalAttribute))
}

// Edit renders a edit form for a FatalAttribute. This function is
// mapped to the path GET /fatal_attributes/{fatal_attribute_id}/edit
func (v FatalAttributesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty FatalAttribute
	fatalAttribute := &models.FatalAttribute{}

	if err := tx.Find(fatalAttribute, c.Param("fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, fatalAttribute))
}

// Update changes a FatalAttribute in the DB. This function is mapped to
// the path PUT /fatal_attributes/{fatal_attribute_id}
func (v FatalAttributesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty FatalAttribute
	fatalAttribute := &models.FatalAttribute{}

	if err := tx.Find(fatalAttribute, c.Param("fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind FatalAttribute to the html form elements
	if err := c.Bind(fatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(fatalAttribute)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, fatalAttribute))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "FatalAttribute was updated successfully")

	// and redirect to the fatal_attributes index page
	return c.Render(200, r.Auto(c, fatalAttribute))
}

// Destroy deletes a FatalAttribute from the DB. This function is mapped
// to the path DELETE /fatal_attributes/{fatal_attribute_id}
func (v FatalAttributesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty FatalAttribute
	fatalAttribute := &models.FatalAttribute{}

	// To find the FatalAttribute the parameter fatal_attribute_id is used.
	if err := tx.Find(fatalAttribute, c.Param("fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(fatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "FatalAttribute was destroyed successfully")

	// Redirect to the fatal_attributes index page
	return c.Render(200, r.Auto(c, fatalAttribute))
}
