package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Metric)
// DB Table: Plural (metrics)
// Resource: Plural (Metrics)
// Path: Plural (/metrics)
// View Template Folder: Plural (/templates/metrics/)

// MetricsResource is the resource for the Metric model
type MetricsResource struct {
	buffalo.Resource
}

// List gets all Metrics. This function is mapped to the path
// GET /metrics
func (v MetricsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	metrics := &models.Metrics{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Metrics from the DB
	if err := q.All(metrics); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, metrics))
}

// Show gets the data for one Metric. This function is mapped to
// the path GET /metrics/{metric_id}
func (v MetricsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Metric
	metric := &models.Metric{}

	// To find the Metric the parameter metric_id is used.
	if err := tx.Find(metric, c.Param("metric_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, metric))
}

// New renders the form for creating a new Metric.
// This function is mapped to the path GET /metrics/new
func (v MetricsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Metric{}))
}

// Create adds a Metric to the DB. This function is mapped to the
// path POST /metrics
func (v MetricsResource) Create(c buffalo.Context) error {
	// Allocate an empty Metric
	metric := &models.Metric{}

	// Bind metric to the html form elements
	if err := c.Bind(metric); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(metric)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, metric))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Metric was created successfully")

	// and redirect to the metrics index page
	return c.Render(201, r.Auto(c, metric))
}

// Edit renders a edit form for a Metric. This function is
// mapped to the path GET /metrics/{metric_id}/edit
func (v MetricsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Metric
	metric := &models.Metric{}

	if err := tx.Find(metric, c.Param("metric_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, metric))
}

// Update changes a Metric in the DB. This function is mapped to
// the path PUT /metrics/{metric_id}
func (v MetricsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Metric
	metric := &models.Metric{}

	if err := tx.Find(metric, c.Param("metric_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Metric to the html form elements
	if err := c.Bind(metric); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(metric)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, metric))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Metric was updated successfully")

	// and redirect to the metrics index page
	return c.Render(200, r.Auto(c, metric))
}

// Destroy deletes a Metric from the DB. This function is mapped
// to the path DELETE /metrics/{metric_id}
func (v MetricsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Metric
	metric := &models.Metric{}

	// To find the Metric the parameter metric_id is used.
	if err := tx.Find(metric, c.Param("metric_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(metric); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Metric was destroyed successfully")

	// Redirect to the metrics index page
	return c.Render(200, r.Auto(c, metric))
}
