package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (OpportunityFatalAttribute)
// DB Table: Plural (opportunity_fatal_attributes)
// Resource: Plural (OpportunityFatalAttributes)
// Path: Plural (/opportunity_fatal_attributes)
// View Template Folder: Plural (/templates/opportunity_fatal_attributes/)

// OpportunityFatalAttributesResource is the resource for the OpportunityFatalAttribute model
type OpportunityFatalAttributesResource struct {
	buffalo.Resource
}

// List gets all OpportunityFatalAttributes. This function is mapped to the path
// GET /opportunity_fatal_attributes
func (v OpportunityFatalAttributesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	opportunityFatalAttributes := &models.OpportunityFatalAttributes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all OpportunityFatalAttributes from the DB
	if err := q.All(opportunityFatalAttributes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, opportunityFatalAttributes))
}

// Show gets the data for one OpportunityFatalAttribute. This function is mapped to
// the path GET /opportunity_fatal_attributes/{opportunity_fatal_attribute_id}
func (v OpportunityFatalAttributesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityFatalAttribute
	opportunityFatalAttribute := &models.OpportunityFatalAttribute{}

	// To find the OpportunityFatalAttribute the parameter opportunity_fatal_attribute_id is used.
	if err := tx.Find(opportunityFatalAttribute, c.Param("opportunity_fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, opportunityFatalAttribute))
}

// New renders the form for creating a new OpportunityFatalAttribute.
// This function is mapped to the path GET /opportunity_fatal_attributes/new
func (v OpportunityFatalAttributesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.OpportunityFatalAttribute{}))
}

// Create adds a OpportunityFatalAttribute to the DB. This function is mapped to the
// path POST /opportunity_fatal_attributes
func (v OpportunityFatalAttributesResource) Create(c buffalo.Context) error {
	// Allocate an empty OpportunityFatalAttribute
	opportunityFatalAttribute := &models.OpportunityFatalAttribute{}

	// Bind opportunityFatalAttribute to the html form elements
	if err := c.Bind(opportunityFatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(opportunityFatalAttribute)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, opportunityFatalAttribute))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OpportunityFatalAttribute was created successfully")

	// and redirect to the opportunity_fatal_attributes index page
	return c.Render(201, r.Auto(c, opportunityFatalAttribute))
}

// Edit renders a edit form for a OpportunityFatalAttribute. This function is
// mapped to the path GET /opportunity_fatal_attributes/{opportunity_fatal_attribute_id}/edit
func (v OpportunityFatalAttributesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityFatalAttribute
	opportunityFatalAttribute := &models.OpportunityFatalAttribute{}

	if err := tx.Find(opportunityFatalAttribute, c.Param("opportunity_fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, opportunityFatalAttribute))
}

// Update changes a OpportunityFatalAttribute in the DB. This function is mapped to
// the path PUT /opportunity_fatal_attributes/{opportunity_fatal_attribute_id}
func (v OpportunityFatalAttributesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityFatalAttribute
	opportunityFatalAttribute := &models.OpportunityFatalAttribute{}

	if err := tx.Find(opportunityFatalAttribute, c.Param("opportunity_fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind OpportunityFatalAttribute to the html form elements
	if err := c.Bind(opportunityFatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(opportunityFatalAttribute)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, opportunityFatalAttribute))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OpportunityFatalAttribute was updated successfully")

	// and redirect to the opportunity_fatal_attributes index page
	return c.Render(200, r.Auto(c, opportunityFatalAttribute))
}

// Destroy deletes a OpportunityFatalAttribute from the DB. This function is mapped
// to the path DELETE /opportunity_fatal_attributes/{opportunity_fatal_attribute_id}
func (v OpportunityFatalAttributesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityFatalAttribute
	opportunityFatalAttribute := &models.OpportunityFatalAttribute{}

	// To find the OpportunityFatalAttribute the parameter opportunity_fatal_attribute_id is used.
	if err := tx.Find(opportunityFatalAttribute, c.Param("opportunity_fatal_attribute_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(opportunityFatalAttribute); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "OpportunityFatalAttribute was destroyed successfully")

	// Redirect to the opportunity_fatal_attributes index page
	return c.Render(200, r.Auto(c, opportunityFatalAttribute))
}
