package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (OpportunityMetric)
// DB Table: Plural (opportunity_metrics)
// Resource: Plural (OpportunityMetrics)
// Path: Plural (/opportunity_metrics)
// View Template Folder: Plural (/templates/opportunity_metrics/)

// OpportunityMetricsResource is the resource for the OpportunityMetric model
type OpportunityMetricsResource struct {
	buffalo.Resource
}

// List gets all OpportunityMetrics. This function is mapped to the path
// GET /opportunity_metrics
func (v OpportunityMetricsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	opportunityMetrics := &models.OpportunityMetrics{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all OpportunityMetrics from the DB
	if err := q.All(opportunityMetrics); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, opportunityMetrics))
}

// Show gets the data for one OpportunityMetric. This function is mapped to
// the path GET /opportunity_metrics/{opportunity_metric_id}
func (v OpportunityMetricsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityMetric
	opportunityMetric := &models.OpportunityMetric{}

	// To find the OpportunityMetric the parameter opportunity_metric_id is used.
	if err := tx.Find(opportunityMetric, c.Param("opportunity_metric_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, opportunityMetric))
}

// New renders the form for creating a new OpportunityMetric.
// This function is mapped to the path GET /opportunity_metrics/new
func (v OpportunityMetricsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.OpportunityMetric{}))
}

// Create adds a OpportunityMetric to the DB. This function is mapped to the
// path POST /opportunity_metrics
func (v OpportunityMetricsResource) Create(c buffalo.Context) error {
	// Allocate an empty OpportunityMetric
	opportunityMetric := &models.OpportunityMetric{}

	// Bind opportunityMetric to the html form elements
	if err := c.Bind(opportunityMetric); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(opportunityMetric)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, opportunityMetric))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OpportunityMetric was created successfully")

	// and redirect to the opportunity_metrics index page
	return c.Render(201, r.Auto(c, opportunityMetric))
}

// Edit renders a edit form for a OpportunityMetric. This function is
// mapped to the path GET /opportunity_metrics/{opportunity_metric_id}/edit
func (v OpportunityMetricsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityMetric
	opportunityMetric := &models.OpportunityMetric{}

	if err := tx.Find(opportunityMetric, c.Param("opportunity_metric_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, opportunityMetric))
}

// Update changes a OpportunityMetric in the DB. This function is mapped to
// the path PUT /opportunity_metrics/{opportunity_metric_id}
func (v OpportunityMetricsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityMetric
	opportunityMetric := &models.OpportunityMetric{}

	if err := tx.Find(opportunityMetric, c.Param("opportunity_metric_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind OpportunityMetric to the html form elements
	if err := c.Bind(opportunityMetric); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(opportunityMetric)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, opportunityMetric))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "OpportunityMetric was updated successfully")

	// and redirect to the opportunity_metrics index page
	return c.Render(200, r.Auto(c, opportunityMetric))
}

// Destroy deletes a OpportunityMetric from the DB. This function is mapped
// to the path DELETE /opportunity_metrics/{opportunity_metric_id}
func (v OpportunityMetricsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty OpportunityMetric
	opportunityMetric := &models.OpportunityMetric{}

	// To find the OpportunityMetric the parameter opportunity_metric_id is used.
	if err := tx.Find(opportunityMetric, c.Param("opportunity_metric_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(opportunityMetric); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "OpportunityMetric was destroyed successfully")

	// Redirect to the opportunity_metrics index page
	return c.Render(200, r.Auto(c, opportunityMetric))
}
