package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ProjectReport)
// DB Table: Plural (project_reports)
// Resource: Plural (ProjectReports)
// Path: Plural (/project_reports)
// View Template Folder: Plural (/templates/project_reports/)

// ProjectReportsResource is the resource for the ProjectReport model
type ProjectReportsResource struct {
	buffalo.Resource
}

// List gets all ProjectReports. This function is mapped to the path
// GET /project_reports
func (v ProjectReportsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	projectReports := &models.ProjectReports{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ProjectReports from the DB
	if err := q.All(projectReports); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, projectReports))
}

// Show gets the data for one ProjectReport. This function is mapped to
// the path GET /project_reports/{project_report_id}
func (v ProjectReportsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ProjectReport
	projectReport := &models.ProjectReport{}

	// To find the ProjectReport the parameter project_report_id is used.
	if err := tx.Find(projectReport, c.Param("project_report_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, projectReport))
}

// New renders the form for creating a new ProjectReport.
// This function is mapped to the path GET /project_reports/new
func (v ProjectReportsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.ProjectReport{}))
}

// Create adds a ProjectReport to the DB. This function is mapped to the
// path POST /project_reports
func (v ProjectReportsResource) Create(c buffalo.Context) error {
	// Allocate an empty ProjectReport
	projectReport := &models.ProjectReport{}

	// Bind projectReport to the html form elements
	if err := c.Bind(projectReport); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(projectReport)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, projectReport))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "ProjectReport was created successfully")

	// and redirect to the project_reports index page
	return c.Render(201, r.Auto(c, projectReport))
}

// Edit renders a edit form for a ProjectReport. This function is
// mapped to the path GET /project_reports/{project_report_id}/edit
func (v ProjectReportsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ProjectReport
	projectReport := &models.ProjectReport{}

	if err := tx.Find(projectReport, c.Param("project_report_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, projectReport))
}

// Update changes a ProjectReport in the DB. This function is mapped to
// the path PUT /project_reports/{project_report_id}
func (v ProjectReportsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ProjectReport
	projectReport := &models.ProjectReport{}

	if err := tx.Find(projectReport, c.Param("project_report_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind ProjectReport to the html form elements
	if err := c.Bind(projectReport); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(projectReport)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, projectReport))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "ProjectReport was updated successfully")

	// and redirect to the project_reports index page
	return c.Render(200, r.Auto(c, projectReport))
}

// Destroy deletes a ProjectReport from the DB. This function is mapped
// to the path DELETE /project_reports/{project_report_id}
func (v ProjectReportsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty ProjectReport
	projectReport := &models.ProjectReport{}

	// To find the ProjectReport the parameter project_report_id is used.
	if err := tx.Find(projectReport, c.Param("project_report_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(projectReport); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "ProjectReport was destroyed successfully")

	// Redirect to the project_reports index page
	return c.Render(200, r.Auto(c, projectReport))
}
