package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/groomly/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Value)
// DB Table: Plural (values)
// Resource: Plural (Values)
// Path: Plural (/values)
// View Template Folder: Plural (/templates/values/)

// ValuesResource is the resource for the Value model
type ValuesResource struct {
	buffalo.Resource
}

// List gets all Values. This function is mapped to the path
// GET /values
func (v ValuesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	values := &models.Values{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Values from the DB
	if err := q.All(values); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, values))
}

// Show gets the data for one Value. This function is mapped to
// the path GET /values/{value_id}
func (v ValuesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Value
	value := &models.Value{}

	// To find the Value the parameter value_id is used.
	if err := tx.Find(value, c.Param("value_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, value))
}

// New renders the form for creating a new Value.
// This function is mapped to the path GET /values/new
func (v ValuesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Value{}))
}

// Create adds a Value to the DB. This function is mapped to the
// path POST /values
func (v ValuesResource) Create(c buffalo.Context) error {
	// Allocate an empty Value
	value := &models.Value{}

	// Bind value to the html form elements
	if err := c.Bind(value); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(value)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, value))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Value was created successfully")

	// and redirect to the values index page
	return c.Render(201, r.Auto(c, value))
}

// Edit renders a edit form for a Value. This function is
// mapped to the path GET /values/{value_id}/edit
func (v ValuesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Value
	value := &models.Value{}

	if err := tx.Find(value, c.Param("value_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, value))
}

// Update changes a Value in the DB. This function is mapped to
// the path PUT /values/{value_id}
func (v ValuesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Value
	value := &models.Value{}

	if err := tx.Find(value, c.Param("value_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Value to the html form elements
	if err := c.Bind(value); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(value)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, value))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Value was updated successfully")

	// and redirect to the values index page
	return c.Render(200, r.Auto(c, value))
}

// Destroy deletes a Value from the DB. This function is mapped
// to the path DELETE /values/{value_id}
func (v ValuesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Value
	value := &models.Value{}

	// To find the Value the parameter value_id is used.
	if err := tx.Find(value, c.Param("value_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(value); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Value was destroyed successfully")

	// Redirect to the values index page
	return c.Render(200, r.Auto(c, value))
}
